import { Context, DateTime, Duration, Effect, Layer, Schema } from "effect";
import { Model } from "effect/unstable/schema";
import { SqlClient, SqlModel, SqlSchema } from "effect/unstable/sql";
import { AddFeedingInput, FeedingId, FeedingView } from "../shared/domain";
import type { OperationUnavailable } from "../shared/errors";
import { storageOperation } from "./storage";

/**
 * A single milk feeding.
 *
 * `Model.Class` derives the database variants (`Feeding` / `Feeding.insert` /
 * `Feeding.update`) from one field declaration:
 *
 * - `id` is a UUID v4 generated by the application on insert
 * - `fedAt` is the (user provided) time the feeding happened, stored as an
 *   ISO-8601 UTC string
 * - `createdAt` is set automatically by the Effect clock on insert
 */
export class Feeding extends Model.Class<Feeding>("Feeding")({
  id: Model.UuidV4Insert(FeedingId),
  ...AddFeedingInput.fields,
  createdAt: Model.DateTimeInsert,
}) {}

const toView = (feeding: Feeding): FeedingView => ({
  id: feeding.id,
  amountMl: feeding.amountMl,
  fedAt: DateTime.formatIso(feeding.fedAt),
  createdAt: DateTime.formatIso(feeding.createdAt),
});

const toIso = (dt: DateTime.DateTime): string => DateTime.formatIso(DateTime.toUtc(dt));

/**
 * Repository service for feedings. The rest of the app depends on `Feedings`
 * instead of the database client, so the storage backend stays swappable.
 */
export class Feedings extends Context.Service<
  Feedings,
  {
    add(input: AddFeedingInput): Effect.Effect<FeedingView, OperationUnavailable>;
    remove(id: FeedingId): Effect.Effect<void, OperationUnavailable>;
    listRecentDays(days: number): Effect.Effect<Array<FeedingView>, OperationUnavailable>;
  }
>()("mampf/server/Feedings") {
  static readonly layer = Layer.effect(
    Feedings,
    Effect.gen(function* () {
      const sql = yield* SqlClient.SqlClient;

      const repo = yield* SqlModel.makeRepository(Feeding, {
        tableName: "feedings",
        spanPrefix: "Feedings",
        idColumn: "id",
      });

      const listSince = SqlSchema.findAll({
        Request: Schema.String,
        Result: Feeding,
        execute: (since) => sql`SELECT * FROM feedings WHERE fedAt >= ${since} ORDER BY fedAt DESC`,
      });

      const add = Effect.fn("Feedings.add")(function* (input: AddFeedingInput) {
        // `Feeding.insert.makeEffect` fills in the generated uuid + `createdAt`
        // using the Effect clock, so tests can control time with `TestClock`.
        const inserted = yield* storageOperation(
          "Feedings.add",
          Feeding.insert.makeEffect(input).pipe(
            Effect.mapError((issue) => new Schema.SchemaError(issue)),
            Effect.flatMap(repo.insert),
          ),
        );
        return toView(inserted);
      });

      const remove = Effect.fn("Feedings.remove")(function* (id: FeedingId) {
        yield* storageOperation("Feedings.remove", repo.delete(id));
      });

      const listRecentDays = Effect.fn("Feedings.listRecentDays")(function* (days: number) {
        const now = yield* DateTime.now;
        const since = toIso(DateTime.subtractDuration(now, Duration.days(days)));
        const rows = yield* storageOperation("Feedings.listRecentDays", listSince(since));
        return rows.map(toView);
      });

      return Feedings.of({ add, remove, listRecentDays });
    }),
  );
  // The `SqlClient` requirement is provided by the runtime (`src/server/runtime.ts`),
  // so the repository stays independent of the concrete database.
}
